### ISSUE TITLE
Tracking issue for first RL

### ISSUE THREAD

**Issue by Deliquescence** [Deliquescence/CapstoneRobot#31]
- [x] Decide on reduced state and action set

- [x] Use tag data to map image/camera -> state

- [ ] Use tag data to map image directly to distance as opposed to pixels. This could potentially be used to make a more interesting reward function.

- [x] After tag mapping is implemented, label the existing training data (state,action,reward,next_state)

- [x] After data is labelled, learn policy

- [x] Connect policy to car follower

- [x] Test policy and observe performance

- [ ] Improve policy (more complex state? better reward function?)
